### ISSUE TITLE
我的教育版弄成了，当然首先我帐号有 api 权限。

### ISSUE THREAD

**Issue by andatoshiki** [andatoshiki/toshiki-lab#1]
我的教育版弄成了，当然首先我帐号有 api 权限。
1. microsoft-graph-api-auth 工具第四步如果在微软那边提示出错的话，这里的`scope`里面的几个权限之间的逗号改成空格。如果是点了还是当前页面，考虑一下 api 是不是设置有误。
2. 然后访问提示`BadRequest`，查了一下应该是 Base 设置为`/`的话就会出现，排查到代码第 242 行，URL 里的`${base+(pathname == "/" ? "" :pathname) }`中`pathname`本身就已经带有`/`，无需再加base了。试着直接改成`${pathname == "/" ? "" : pathname}`，可以了。

**Comment by chenskiro** [comment]
总感觉这标题很奇怪（？

**Comment by andatoshiki** [comment]
> 总感觉这标题很奇怪（？

這只是一個類似於備忘錄的東西
